import Head from 'next/head'
import { useState } from 'react'

import { BsFillMoonStarsFill } from 'react-icons/bs'
import { FaGithub, FaLinkedin } from "react-icons/fa";
import Image from "next/image";

import facu from "../public/Dibujo_sFondo.png";
import Melinder2 from "../public/melinderPortfolio.jpg";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [Lang, setLang] = useState(`ESP`)
  const languageHandler = () => Lang === `ESP` ? setLang('ENG') : setLang('ESP')

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Facundo Rubino Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white md:px-10 lg:px-15 dark:bg-gray-900 transition-all ">
        <section className="mb-10">
          <nav className="px-3 pt-6 grid justify-items-end">
            <ul className="flex">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-slate-200" />
              </li>
              <li><a onClick={() => languageHandler()} className="bg-gradient-to-r from-orange-300 to-orange-500 text-white px-4 py-2 rounded-md ml-4 cursor-pointer" >{Lang}</a></li>
            </ul>
          </nav>
          <div className="text-center p-5">
            <h2 className="text-3xl py-2 font-medium md:text-4xl dark:text-slate-200 ">Facundo Rubino</h2>
            <h3 className="text-4xl font-extrabold uppercase text-transparent bg-clip-text bg-gradient-to-r from-orange-300 to-orange-500">{Lang == `ESP` ? `Desarrollador FrontEnd ` : `FrontEnd Developer `}</h3>
            <p className="text-md pt-3 leading-7 text-gray-800 dark:text-slate-200 w-11/12 md:w-8/12 m-auto ">{Lang == `ESP` ? `Como persona organizada, responsable y con una gran motivación, soy capaz de adaptarme a cualquier circunstancia, dar siempre lo mejor de mí en cualquier proyecto y disfrutar de trabajar en equipo.
              Dado mi trayecto académico, como diseñador y desarrollador, me encuentro en la búsqueda de definirme como un perfil Full Stack, capaz de dar soluciones eficientes, lógicas y versátiles.`
              : ` As an organized, responsible, and highly motivated individual, I am capable of adapting to any circumstance, always giving my best in any project, and enjoying working in a team.
              Given my academic background as a designer and developer, I am currently seeking to define myself as a Full Stack profile, capable of providing efficient, logical, and versatile solutions.`}
            </p>
          </div>
          <div className="text-2xl flex justify-center gap-6 text-gray-500  ">
            <a href="https://www.linkedin.com/in/facundo-rubino/" target="_blank"><FaLinkedin /></a>
            <a href="https://github.com/facundo-rubino" target="_blank"><FaGithub /></a>

          </div>
          <div className="relative mx-auto bg-gradient-to-b from-orange-500 rounded-full w-60 h-60 mt-5 overflow-hidden">
            <Image src={facu} className="ml-6 mt-3" layout="" objectFit="" />
          </div>

        </section>

        {/* Tools */}
        <section>
          <div>
            <h3 className="text-3xl mt-5 uppercase font-medium text-transparent bg-clip-text bg-gradient-to-r from-orange-300 to-orange-500 text-center ">{Lang === `ESP` ? `Tecnologías que manejo` : `Technological Expertise`}</h3>
            <p className="text-center dark:text-slate-200 py-3">{Lang === `ESP` ? `A lo largo de los años fui desarrollando nuevas habilidades` : `Over the years, I have cultivated a diverse skill set.`}</p>
          </div>
          {/* Tools container */}
          <div className="flex flex-wrap mb-5 w-10/12 justify-center items-center m-auto md:w-6/12">
            <div className="flex-shrink-0 p-2">
              <div className="bg-slate-100 rounded-md p-2">
                JavaScript
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                C#
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                ReactJs
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                ASP .NET-7.0
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                SQL
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                HTML
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                Css
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                TailwindCss
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                Git
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                Github
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                MER/MR
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                MVC
              </div>
            </div>
            <div className="flex-shrink-0 p-2">
              <div className="bg-gray-100 rounded-md p-2">
                UML
              </div>
            </div>
          </div>
        </section>

        {/* Portfolio */}
        <section>
          <h3 className="text-3xl pt-10 uppercase font-medium text-transparent bg-clip-text bg-gradient-to-r from-orange-300 to-orange-500 text-center ">Portfolio</h3>

          {/* Portfolio container */}
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 py-10 lg:flex-row lg:flex-wrap">
            <div className="shadow-xl w-11/12 m-auto ">
              <a href="https://melinder-app.vercel.app/" target="_blank"> <Image src={Melinder2} className="rounded-lg object-fill shadow-sm cursor-pointer" width={'100%'} height={'100%'} layout="responsive" /></a>
            </div>
          </div>
        </section>
      </main>
    </div >
  );
}
