import Head from 'next/head'
import { useState } from 'react'

import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillInstagram, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";

import rulo from "../public/rulo.svg";
import facu from "../public/Dibujo_sFondo.png";
import Melinder2 from "../public/melinderPortfolio.jpg"
import web1 from "../public/web1.png"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [Lang, setLang] = useState(`ESP`)
  const languageHandler = () => Lang === `ESP` ? setLang('ENG') : setLang('ESP')

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Facundo Rubino Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-5 md:px-10 lg:px-15 dark:bg-gray-900 transition-all ">
        <section className="min-h-screen">
          <nav className="p-10 mb-2 flex justify-between">
            <div>
              <Image src={rulo} height={30} width={30} className="inline-block mr-3 dark:fill-slate-200" />
              <h1 className="text-xl dark:text-slate-200 inline-block">Facundo Rubino</h1>
            </div>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-slate-200" />
              </li>
              <li><a onClick={() => languageHandler()} className="bg-gradient-to-r from-orange-300 to-orange-500 text-white px-4 py-2 rounded-md ml-8 cursor-pointer" >{Lang}</a></li>
            </ul>
          </nav>
          <div className="text-center p-5">
            <h2 className="text-3xl py-2 text-gradient-to-r from-orange-300 to-orange-500 font-medium md:text-4xl">Facundo Rubino</h2>
            <h3 className="text-4xl font-extrabold uppercase text-transparent bg-clip-text bg-gradient-to-r from-orange-300 to-orange-500">{Lang == `ESP` ? `Desarrollador FrontEnd ` : `FrontEnd Developer `}</h3>
            <p className="text-md py-3 leading-7 text-gray-800 dark:text-slate-200">{Lang == `ESP` ? `Como persona organizada, responsable y con una gran motivación, soy capaz de adaptarme a cualquier circunstancia, dar siempre lo mejor de mí en cualquier proyecto y disfrutar de trabajar en equipo.
              Dado mi trayecto académico, me encuentro en la búsqueda de definirme como un perfil Full Stack, capaz de dar soluciones eficientes, lógicas y versátiles.`
              : ` I received my degree in Multimedia Design at Universidad ORT Uruguay, where I learned technologies such as HTML, CSS, Javascript, React JS, PHP, Ionic, and Bootstrap. I am currently studying to become a IT Analyst at the same university, where I am learning new backend skills with the goal of building a Full Stack profile. In my free time, I have also been taking courses in Tailwind Css and Flutter/Dart.`}
            </p>
          </div>
          <div className="text-2xl flex justify-center gap-8 pb-3 text-gray-500 ">
            <AiFillLinkedin /><AiFillGithub /><AiFillInstagram />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-orange-500 rounded-full w-60 h-60 mt-10 overflow-hidden">
            <Image src={facu} className="ml-6 mt-3" layout="" objectFit="" />
          </div>
        </section>

        {/* Tools */}
        <section>
          <div>
            <h3 className="text-3xl py-1 text-red-600 text-center dark:text-red-200">{Lang === `ESP` ? `Tecnologías que manejo` : `Tools that I handle`}</h3>
            <p className="text-center dark:text-slate-200">{Lang === `ESP` ? `A lo largo de los años fui desarrollando nuevas habilidades` : `skills`}</p>
          </div>
          {/* Tools container */}
          <div className="flex flex-wrap mt-5 mb-5 w-10/12 justify-center items-center m-auto">
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                JavaScript
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                C#
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                ReactJs
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                ASP .NET-7.0
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                SQL
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                HTML
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                Css
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                TailwindCss
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                Git
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                Github
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                MER/MR
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                MVC
              </div>
            </div>
            <div class="flex-shrink-0 p-2">
              <div class="bg-gray-100 rounded-md p-2">
                UML
              </div>
            </div>
          </div>
        </section>

        {/* Portfolio */}
        <section>
          <div>
            <h3 className="text-3xl py-1 text-red-600 dark:text-slate-200">Portfolio</h3>
          </div>
          {/* Portfolio container */}
          <div className="grid md:grid-cols-3 gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="shadow-xl ">
              <a href="https://melinder-app.vercel.app/" target="_blank"> <Image src={Melinder2} className="rounded-lg object-fill shadow-sm cursor-pointer" width={'100%'} height={'100%'} layout="responsive" /></a>
            </div>
            <div className="">
              <a href="https://melinder-app.vercel.app/" target="_blank"> <Image src={Melinder2} className="rounded-lg object-fill" width={'100%'} height={'100%'} layout="responsive" /></a>
            </div>
            <div className="">
              <a href="https://melinder-app.vercel.app/" target="_blank"> <Image src={Melinder2} className="rounded-lg object-fill" width={'100%'} height={'100%'} layout="responsive" /></a>
            </div>



          </div>

        </section>

      </main>
    </div >
  );
}
